apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-kube-deployment
spec:
  selector:
    matchLabels:
      app: go-kube
  replicas: 1
  template:
    metadata:
      labels:
        app: go-kube 
    spec:
        containers:
        - name: go-kube
          image: alextanhongpin/go-kube
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: go-kube-service
spec:
  type: NodePort
  selector:
    app: go-kube
  ports:
  - protocol: TCP
    port: 8080 
    targetPort: 8080
    nodePort: 30000 
